feat:add sort for get repo list
katanomi/pkg pull request #152
Opened 2022-01-10 05:21 UTC by XiaoBoya

2022-01-10 08:36 UTC, chengjingtao requested changes

2022-01-10 08:36 UTC, chengjingtao commented on apis/meta/v1alpha1/listmeta_types.go
> +	Order string `json:"desc"`
`json:"desc"` 写错了？

2022-01-10 08:36 UTC, chengjingtao commented on apis/meta/v1alpha1/listmeta_types.go
> +	Order string `json:"desc"`
type SortOrder string 
var	OrderDesc SortOrder = "desc"
var	OrderAsc  SortOrder = "asc"

2022-01-10 08:36 UTC, chengjingtao commented on plugin/route/options.go
> +		sortOptions.Order = "desc"
定义好的变量OrderDesc为啥不用？

2022-01-11 02:09 UTC, danielfbm requested changes

2022-01-11 02:09 UTC, danielfbm commented on plugin/route/options.go
> +	"yunion.io/x/log"
这个不太对吧

2022-01-11 02:09 UTC, danielfbm commented on plugin/route/options.go
> +		log.Errorln("sortBy", sortBy, "info", "It is singular after cutting, so it is impossible to obtain valid sorting conditions.Ignore sortBy!!!")
要使用我们已经有的logger，如果需要提供的话可以通过提供一个context 变量，从context取

2022-01-11 02:09 UTC, danielfbm commented on plugin/route/options.go
> +				log.Errorln("sortBy", sortBy, "order", v, "info", "unknown order type")
同上

2022-01-11 02:09 UTC, danielfbm commented on apis/meta/v1alpha1/gitrepositories_types.go
> +	CodeRepoSortKeyForName   = "repoName"
这个key是为了按名称排序么？建议做一个统一的，不要只考虑自己的问题，上周已经讨论过多次这种事儿

2022-01-11 02:09 UTC, danielfbm commented on apis/meta/v1alpha1/gitrepositories_types.go
> +	CodeRepoSortKeyForName   = "repoName"
换成`NameSortKey` 和 `UpdatedTimeSortKey` ?

2022-01-11 05:45 UTC, XiaoBoya commented on plugin/route/options.go
> +	"yunion.io/x/log"
"knative.dev/pkg/logging" 修改

2022-01-11 05:46 UTC, XiaoBoya commented on plugin/route/options.go
> +		log.Errorln("sortBy", sortBy, "info", "It is singular after cutting, so it is impossible to obtain valid sorting conditions.Ignore sortBy!!!")
logger := logging.FromContext(ctx).Named("SortParamHandler")

2022-01-11 09:13 UTC, danielfbm commented on apis/meta/v1alpha1/listmeta_types.go
> +	UpdatedTimeSortKey SortBy = "update"
"updatedTime"

2022-01-11 09:19 UTC, danielfbm requested changes

2022-01-11 09:19 UTC, danielfbm commented on plugin/route/options_test.go
> +	var sortByA = "asc,a,desc,b"
这个是  a asc 同时 b desc 么？
分隔字符最好不一样？

2022-01-11 09:19 UTC, danielfbm commented on plugin/route/options_test.go
> +
这个测试写法有点不太理想，所有的case都写到外面，跟里面的 context关联不直观。
建议这样改：
外面定义一个 sortBy 变量和 context
```
var sortBy = ""
var context = context.Background()
```
Describe里面 context外面 添加一个统一的调度函数

```
JustBeforeEach(func(){
  res = HandleSortQuery(cox, sortBy)
})
```

每个context里面只要设置sortBy就可以了，比如

```
BeforeEach(func() {
  sortBy = "asc,a,desc,b"
})
```

2022-01-11 09:52 UTC, danielfbm submitted a review, later dismissed

2022-01-11 15:46 UTC, chengjingtao approved these changes

2022-01-11 15:57 UTC, merged