feat:add function to list commit and add additional information to co…
katanomi/pkg pull request #161
Opened 2022-01-17 04:13 UTC by XiaoBoya

# Changes

add function for list commit and add additional information to commit

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [√] [`spec` feat/add-doc-for-listcommit](https://github.com/katanomi/spec/pull/82) included
- [√] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [√] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [√] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [√] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

API changes

For pull requests with a release note:

```release-note
add function list commit and add additional information to commit
```

2022-01-26 01:45 UTC, danielfbm requested changes

2022-01-26 01:45 UTC, danielfbm commented on apis/meta/v1alpha1/gitcommit_types.go
> +	// Address for commit url for code repository web server
CreateAt 有个type，应该是 `CreatedAt`

2022-01-26 01:45 UTC, danielfbm commented on apis/meta/v1alpha1/gitoption_types.go
> +	Until *v1.Time `json:"util,omitempty"`
加注释？

2022-01-26 01:45 UTC, danielfbm commented on plugin/route/gitcommit.go
> +func HandleTimeParamInQuery(param string) (res *v1.Time, err error) {
注释

2022-01-26 01:45 UTC, danielfbm commented on plugin/client/gitcommit.go
> +	}
这个问题跟科燃的PR是一个问题，你们达成一致一个方案统一修复吧

现在新添加的插件函数/API在这里调度会导致 404 错误（路由不能存在），用户不好判断到底是代码仓库不存在，还是啥问题，你们一起考虑一个方案哈

2022-01-26 01:45 UTC, danielfbm commented on plugin/route/options.go
> +		logger.Errorw("It is singular after cutting, so it is impossible to obtain valid sorting conditions.Ignore sortBy!!!", SortQueryKey, url.QueryEscape(sortBy))
`"It is singular after cutting, so it is impossible to obtain valid sorting conditions.Ignore sortBy!!!"` > `"sortBy is expected to be in pairs ignoring sort by..."`

然后在values里面加 sortInfoList 的len

2022-02-07 13:46 UTC, XiaoBoya commented on plugin/client/gitcommit.go
> +	}
https://github.com/katanomi/spec/pull/92

2022-02-08 02:33 UTC, danielfbm approved these changes

2022-02-11 05:17 UTC, danielfbm approved these changes

2022-03-11 06:11 UTC, danielfbm approved these changes

2022-03-11 06:12 UTC, merged