feat: add dynamic auth type
katanomi/pkg pull request #194
Opened 2022-04-07 14:25 UTC by kycheng

# Changes

- add dynamic define.
- add ListOption default pager.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

2022-04-14 01:35 UTC, kycheng commented on apis/meta/v1alpha1/auth_types.go
> +	AuthTokenStatus
用于动态密钥过期时间的返回

2022-04-14 02:01 UTC, kycheng commented
lint 由于github 使用golang1.18 导致

2022-04-14 03:47 UTC, airycanon commented on apis/meta/v1alpha1/auth_types.go
> +	AuthTokenStatus
这里返回了 AuthTokenStatus 的 username 和 password 给前端，会有安全问题？

2022-04-14 04:23 UTC, danielfbm requested changes
除了评论的内容，看一下lint错误一起修复？

2022-04-14 04:23 UTC, danielfbm commented on apis/meta/v1alpha1/auth_types.go
> +	AuthTokenStatus
+1 感觉不应该直接返回所有的数据，是不是可以选择性挑需要的字段呢？

2022-04-15 03:06 UTC, airycanon approved these changes

2022-04-15 03:48 UTC, danielfbm commented on apis/meta/v1alpha1/auth_types.go
> +	ReflushData *AuthTokenStatus `json:"reflushData,omitempty"`
Reflush 是 `重新冲水` 的意思，应该是刷新？`RefreshData` ?

2022-04-15 03:58 UTC, danielfbm submitted a review, later dismissed

2022-04-18 05:55 UTC, danielfbm approved these changes

2022-04-18 05:56 UTC, merged