Feat/tracing
katanomi/pkg pull request #200
Opened 2022-04-25 11:45 UTC by nanjingfm

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2022-04-27 04:57 UTC, danielfbm requested changes

2022-04-27 04:57 UTC, danielfbm commented on testing/mock/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
> +/*
之前我记得这些 testing/mock 目录的会忽略，你确认一下？

2022-04-27 04:57 UTC, danielfbm commented on tracing/filter.go
> +Copyright 2021 The Katanomi Authors.
Copyright之前不是统一改了2022？

2022-04-28 02:25 UTC, danielfbm approved these changes

2022-05-05 08:22 UTC, nanjingfm commented on tracing/config.go
> +	defaultConfigMapName = "katanomi-config-tracing"
默认的配置文件名和knative使用的配置文件名冲突了，换了一个名字

2022-05-05 10:25 UTC, danielfbm approved these changes

2022-05-05 10:34 UTC, chengjingtao approved these changes

2022-05-05 14:58 UTC, merged