Feat/artifactcleanup
katanomi/pkg pull request #211
Opened 2022-05-26 09:16 UTC by kycheng

# Changes

add delete tag interface.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

2022-05-26 10:09 UTC, kycheng commented on apis/meta/v1alpha1/artifact_types.go
> +	PullTime metav1.Time `json:"pullTime,omitempty"`
harbor支持拉取时间

2022-05-26 11:22 UTC, kycheng commented on go.mod
> +require golang.org/x/net v0.0.0-20210917221730-978cfadd31cf
transport test 依赖https://github.com/katanomi/pkg/blob/main/tracing/transport_test.go#L33

2022-06-09 07:53 UTC, danielfbm requested changes

2022-06-09 07:53 UTC, danielfbm commented on apis/meta/v1alpha1/artifact_types.go
> +	PullTime metav1.Time `json:"pullTime,omitempty"`
这个pulltime如果没填的话会返回什么值？是不是应该是 `*metav1.Time` ?

2022-06-09 07:53 UTC, danielfbm commented on plugin/client/artifact.go
> +	Delete(ctx context.Context, baseURL *duckv1.Addressable, project string, repsitory string, artifact string, options ...OptionFunc) error
typo? `repsitory` > `repository` ?

2022-06-09 07:53 UTC, danielfbm commented on plugin/client/artifact.go
> +	Delete(ctx context.Context, baseURL *duckv1.Addressable, project string, repsitory string, artifact string, options ...OptionFunc) error
下面也是

有个问题，如果没有实现这个接口还能做制品清理么？

2022-06-09 07:53 UTC, danielfbm commented on plugin/client/interface.go
> +	DeleteArtifactTag(ctx context.Context, params metav1alpha1.ArtifactTagOptions) error
这个跟上面的那个什么区别？

2022-06-09 07:53 UTC, danielfbm commented on plugin/client/testdata/artifactlist.yaml
> +              { "url": "https://build-harbor.alauda.cn/3rdparty/minio/mc" },
这个？？？

2022-06-09 07:53 UTC, danielfbm commented on plugin/client/testdata/artifactlist.yaml
> +                "url": "https://build-harbor.alauda.cn/harbor/projects/15/repositories/3rdparty/minio/minio",
内部地址最好不要暴漏

2022-06-09 07:53 UTC, danielfbm commented on plugin/route/route.go
> +
ClientArtifact 这个不需要么

2022-06-09 07:57 UTC, kycheng commented on plugin/client/testdata/artifactlist.yaml
> +              { "url": "https://build-harbor.alauda.cn/3rdparty/minio/mc" },
测试数据

2022-06-09 07:57 UTC, kycheng commented on plugin/client/testdata/artifactlist.yaml
> +                "url": "https://build-harbor.alauda.cn/harbor/projects/15/repositories/3rdparty/minio/minio",
我把地址修改一下

2022-06-09 08:01 UTC, kycheng commented on plugin/client/interface.go
> +	DeleteArtifactTag(ctx context.Context, params metav1alpha1.ArtifactTagOptions) error
以修改注释。

2022-06-09 08:07 UTC, kycheng commented on plugin/client/artifact.go
> +	Delete(ctx context.Context, baseURL *duckv1.Addressable, project string, repsitory string, artifact string, options ...OptionFunc) error
不能做，我们会在创建制品清理的时候做过滤，没有实现这个方法的插件无法创建。

2022-06-09 08:15 UTC, danielfbm commented on plugin/client/testdata/artifactlist.yaml
> +                "imageRegistryEndpoint": "build-harbor.alauda.cn",
这些build-harbor的东西都换成别的哈

2022-06-09 08:16 UTC, danielfbm commented on plugin/client/interface.go
> +// ArtifactTagDeleter delete artifact
建议用心写一下这个接口的作用，假设我们要通过这些注释直接生产文档，开发者要如何了解这个是干什么用的？

2022-06-09 09:01 UTC, kycheng commented on plugin/route/route.go
> +
这里是添加的interface就可以了，不用加client

2022-06-09 09:22 UTC, danielfbm approved these changes

2022-06-09 09:23 UTC, merged