feat(testing): add e2e testing framework
katanomi/pkg pull request #220
Opened 2022-06-14 07:29 UTC by nanjingfm

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [`spec` PR link](https://github.com/katanomi/spec) included
- [x] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [x] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [x] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2022-06-15 11:14 UTC, nanjingfm commented on testing/framework/config.go
> +	testCtx.Context = context.WithValue(testCtx.Context, configCondition{}, c.obj)
将插件的配置塞到context中，后面有类似自定义的全局性的东西（配置、client）都可以塞到context中。

2022-06-15 11:15 UTC, nanjingfm commented on testing/framework/config.go
> +	c.once.Do(func() {
通常用于测试初始化阶段，配置只取一次。

2022-06-15 11:17 UTC, nanjingfm commented on testing/framework/context.go
> +	Client  client.Client
k8s client，因为用的比较多，所以就单独加了个字段（而没有塞到context中）

2022-06-15 11:34 UTC, danielfbm requested changes

2022-06-15 11:34 UTC, danielfbm commented on testing/framework/config.go
> +	e2eConfigNamePrefix = GetDefaultEnv(e2eConfigNameKey, "e2e-config")
这些环境变量需要在readme里面提供说明？

2022-06-15 11:34 UTC, danielfbm commented on testing/framework/env_test.go
> +package framework
test文件也需要copyright license信息？

2022-06-20 05:50 UTC, danielfbm approved these changes

2022-06-20 15:45 UTC, merged