feat: add constants for versioning
katanomi/pkg pull request #228
Opened 2022-07-21 16:17 UTC by l-qing

# Changes
feat: add constants for versioning

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] https://github.com/katanomi/spec/pull/140
- [X] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [X] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [X] Release notes block below has been filled in or deleted (only if no user facing changes)

2022-07-21 16:32 UTC, l-qing commented on apis/meta/v1alpha1/condition.go
> +	ConditionTrue ConditionType = "True"
版本策略的状态是：`True`、`Fales`、`Unknown`。
而其他地方地方声明的状态类型是：`ConditionType `
https://github.com/katanomi/pkg/blob/03a55b74677fd665b832fe78ce8330498800f46b/apis/meta/v1alpha1/gitcommitstatus_types.go#L48-L58

2022-07-21 16:32 UTC, l-qing commented on apis/meta/v1alpha1/gitcommitstatus_types.go
> +	StatusInfoTypeVersionKey           = "version"
这是本次新增的类型。

2022-07-21 16:32 UTC, l-qing commented on apis/meta/v1alpha1/gitcommitstatus_types.go
> +	CommitStatusStatePending  CommitStatusStateType = "pending"
从 builds 代码仓库拷贝过来的，之前它少了一个 pending 状态，这次也补上。
core 在更新 version 信息时也会用到该类型。

https://github.com/katanomi/builds/blob/7297852076237073827c44a67f36dcb584a8b240/pkg/apis/builds/v1alpha1/buildrun_types.go#L340-L347

2022-07-21 16:32 UTC, l-qing commented on apis/meta/v1alpha1/labels_annotations.go
> +	SecretSyncMutationLabelKey = "integrations.katanomi.dev/integration.mutation"
在 spec 文档中很早就有该注解的描述了：
https://github.com/katanomi/spec/blob/main/2.common.labels.annotations.md

但目前还是有些代码仓库自己定义了该值，比如：
* https://github.com/katanomi/integrations/blob/65a99fbea67a300f25af8f58a570085d61466984/pkg/apis/integrations/v1alpha1/labels_annotations.go#L28
* https://github.com/katanomi/builds/blob/7297852076237073827c44a67f36dcb584a8b240/pkg/apis/builds/v1alpha1/constant.go#L25

2022-07-22 01:19 UTC, danielfbm requested changes

2022-07-22 01:19 UTC, danielfbm commented on apis/meta/v1alpha1/gitcommitstatus_types.go
> +	CommitStatusStatePending  CommitStatusStateType = "pending"
这个不应该跟某个工具耦合，我们可以有自己的抽象，这个抽象最好使用我们的格式 `PascalCase` ?

2022-07-22 01:19 UTC, danielfbm commented on apis/meta/v1alpha1/condition.go
> +	ConditionTrue ConditionType = "True"
GitCommitStatusInfo 直接用  corev1.ConditionStatus 是不是就不要把True，False 和 Unknown当作condition？这几个值不像condition而像状态，是不是保持我们现有的标准更好？

2022-07-22 04:10 UTC, l-qing commented on apis/meta/v1alpha1/gitcommitstatus_types.go
> +const (
参考了 GitLab 和 GitHub 的。
https://github.com/xanzy/go-gitlab/blob/1ca150701fc8084feb459296cbd8b8a5ca8c544b/types.go#L224-L237
https://docs.github.com/en/rest/commits/statuses

2022-07-22 04:11 UTC, danielfbm approved these changes

2022-07-22 04:16 UTC, merged