feat: test management
katanomi/pkg pull request #240
Opened 2022-08-08 06:21 UTC by kinsolee

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2022-08-19 08:57 UTC, danielfbm commented on apis/meta/v1alpha1/testcase_types.go
> +type TestCaseRelatedObjectInfo struct {
public types 加注释， 可选字短加  `// +optional` 注释

2022-08-19 09:00 UTC, danielfbm commented on plugin/client/interface.go
> +}
interface需要加一下注释介绍

2022-08-22 02:40 UTC, chengjingtao requested changes

2022-08-22 02:40 UTC, chengjingtao commented on apis/meta/v1alpha1/testmodule_types.go
> +	TestObjectRef `json:"ref"`
为啥这里不做成一个字段呢？
```
type TestModuleCaseRef struct {
	// TestObjectRef refers to a test case
	TestCase TestObjectRef `json:"ref"`
}
```

现在 TestObjectRef 是一个抽象的表达， 在不同场景下代表的含义不同。
```
type TestCaseExecutionSpec struct {
	// TestPlanID refers to the test plan including current test case
	TestPlanID string `json:"testPlanId"`

	// BuildRef refers to the build related to current test case
	// +optional
	BuildRef *TestObjectRef `json:"buildRef"`
}
```

没有字段名称，很难理解TestModuleCaseRef. TestObjectRef 代表的是啥意思

2022-08-22 02:40 UTC, chengjingtao commented on apis/meta/v1alpha1/testplan_types.go
> +func GetRefByIDFromMap(m map[string]*TestObjectRef, ID string) *TestObjectRef {
当前的包名是 metav1alpha1, 从 metav1alpha1. GetRefByIDFromMap  来看，这个命名不太合适。
换个名称？

2022-08-22 02:40 UTC, chengjingtao commented on plugin/client/testcaseexecution.go
> +type ClientTestCaseExecution interface {
加注释

2022-08-22 02:40 UTC, chengjingtao commented on plugin/client/testmodule.go
> +type ClientTestModule interface {
同上

2022-08-22 02:40 UTC, chengjingtao commented on plugin/route/testcase.go
> +		),
缺少权限控制， 其他 API 类似

2022-08-23 11:26 UTC, chengjingtao approved these changes

2022-08-23 11:28 UTC, merged