Better error handling
katanomi/pkg pull request #32
Opened 2021-08-17 08:04 UTC by airycanon

This pr include: 
* better error handling
* get project interface
* minor bug fix

2021-08-17 09:22 UTC, NigelZHANG submitted a review, later dismissed

2021-08-17 09:32 UTC, danielfbm requested changes

2021-08-17 09:32 UTC, danielfbm commented on plugin/client/plugin_client.go
> +	defaultClient = resty.New()
不太建议这样做，主要原因是默认就变成了所有的客户端都是一样的，虽然在初始化一个客户端 （PluginClient）但是内部还是统一的resty client, 这个逻辑对用户不透明的，希望默认情况还是每次初始化一个新的 resty client，用户端需要提供一个客户端才能满足复用的场景

避免全局变量

2021-08-17 09:32 UTC, danielfbm commented on plugin/client/plugin_client.go
> +		}
复用pkg里面已有的函数

2021-08-18 07:24 UTC, danielfbm commented on plugin/route/project.go
> +		Doc("CreateProject").
函数名字不对？

2021-08-19 01:58 UTC, danielfbm approved these changes

2021-08-19 02:35 UTC, merged