feat: add storage plugin related structs
katanomi/pkg pull request #360
Opened 2023-01-16 05:51 UTC by kinsolee

# Changes
1. add capability type to support StoragePluginClass status.
2. add FileMeta structs for API entity.
3. add archive and file-store interfaces.
4. add tekton Params structs alias.
5. abstract plugin addressable url to an embedded struct.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-01-16 05:55 UTC, kinsolee commented on plugin/client/plugin_client.go
> +	// DefaultOptions for default plugin client options
默认Options变成public，这样StoragePluginClient可以复用

2023-01-16 05:56 UTC, kinsolee commented on plugin/client/interface.go
> +// PluginAddressable provides methods to get plugin address url
拆成细粒度接口，StoragePluginRegister 可以复用

2023-01-16 05:59 UTC, kinsolee commented on plugin/plugin_base.go
> +type DefaultPluginAddresser struct{}
封装Addresser，PluginRegister和StoragePluginRegister可以embed复用

2023-01-16 06:29 UTC, kinsolee commented on plugin/storage/client/client.go
> +	*client.PluginClient
先复用 client.PluginClient 的方法，重写方法先去掉secret和meta header，后续有进一步授权方案再优化

2023-01-17 05:20 UTC, chengjingtao commented on apis/meta/v1alpha1/filemeta_types.go
> +	FileType string `json:"fileType"`
FileType 我们需要定义一个枚举， 提前定义出来。

2023-01-17 06:35 UTC, kinsolee commented on apis/meta/v1alpha1/filemeta_types.go
> +	FileType string `json:"fileType"`
这里是不是可以直接使用 contract.ContractType 作为type字段类型，之前讨论的结论是跟 contract 对齐

2023-01-18 02:43 UTC, chengjingtao requested changes

2023-01-18 02:43 UTC, chengjingtao commented on plugin/storage/capabilities.go
> +		if reflect.TypeOf(obj).Implements(iElem) {
把 reflect.TypeOf(obj) 放到 for 循环外？ 同时 RegisteredCapabilities 的reflect.TypeOf(x).Elem() 可以考虑 做到init 初始化出来？ 每次都反射一次不太值当。

2023-01-18 02:43 UTC, chengjingtao commented on plugin/storage/capabilities.go
> +func GetImplementedCapabilities(obj interface{}) Capabilities {
这个方法什么时候会用到呢？

2023-01-18 02:43 UTC, chengjingtao commented on plugin/storage/capabilities/filestore/v1alpha1/interface.go
> +	FileReader io.Reader
感觉上可能需要是 io.ReaderCloser 。 后边注意下就行。

2023-01-18 02:43 UTC, chengjingtao commented on plugin/storage/client/client.go
> +const HeaderFileAnnotationPrefix = "x-katanomi-annotation-"
大小写我们保持一致？都用小写？ 不过对于header而言，貌似是不区分大小写的
x-katanomi-meta
x-katanomi-annotation-

2023-01-18 02:43 UTC, chengjingtao commented on plugin/storage/route.go
> +func GetPluginWebPath(c client.Interface) string {
这个啥时候会用呀， 换成 GetPluginAPIPath ?

2023-01-18 03:53 UTC, kinsolee commented on plugin/storage/capabilities.go
> +func GetImplementedCapabilities(obj interface{}) Capabilities {
这个方法在 storagepluginclass_controller 获取 StoragePluginClass.status.capabilities 时调用

2023-01-18 03:56 UTC, kinsolee commented on plugin/storage/route.go
> +func GetPluginWebPath(c client.Interface) string {
这里用来获取 storagepluginclass 的API path路径，不同的class路径不一样

2023-01-18 06:24 UTC, chengjingtao approved these changes

2023-01-18 06:29 UTC, merged