fix: add update manager config in updateFunc.
katanomi/pkg pull request #387
Opened 2023-02-16 06:32 UTC by kycheng

# Changes

1. add update manager config in updateFunc.
2. remove version generate.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

2023-02-16 07:06 UTC, kycheng commented on apis/meta/v1alpha1/buildmetadata_types.go
> +	VersionPhase string `json:"versionPhase,omitempty" variable:"-"`
版本策略的变量统一走build.status 生成。

2023-02-16 07:11 UTC, danielfbm commented on config/feature_watch.go
> +
predicate里面加这个功能不合适

2023-02-16 07:12 UTC, l-qing commented on config/manager.go
> +	manager.lock.Unlock()
一般是用 defer ？

2023-02-16 07:12 UTC, danielfbm requested changes
留了评论

2023-02-16 10:15 UTC, danielfbm commented on config/feature_watch.go
> +		}
不应该更新manager的数据，它自己有更新机制，这里保持只读操作

2023-02-18 12:30 UTC, danielfbm commented on config/feature_watch.go
> +			if cm.ResourceVersion == manager.GetResourceVersion() {
cm.ResourceVersion >= manager.GetResourceVersion ? 这里得把它当int来处理

2023-02-18 12:33 UTC, danielfbm commented on config/feature_watch.go
> +		manager.WaitWatchResourceApply(ctx, new)
这种操作放在 event handler 那种函数合适，这个predicate可以理解为一个过滤条件而已，那个函数可以处理timeout的情况，比如timeout就不reconcile或者reconcile所有的？

2023-02-20 01:43 UTC, danielfbm approved these changes

2023-02-20 01:43 UTC, merged