feat: implement ktn-task command
katanomi/pkg pull request #393
Opened 2023-02-21 08:21 UTC by kinsolee

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-03-01 08:30 UTC, kinsolee commented on plugin/storage/capabilities/archive/v1alpha1/interface.go
> +//go:generate ../../../../../bin/mockgen -source=interface.go -destination=../../../../../testing/mock/github.com/katanomi/pkg/plugin/storage/capabilities/archive/v1alpha1/interface.go -package=v1alp
统一mock文件生成路径

2023-03-01 08:31 UTC, kinsolee commented on plugin/storage/client/client.go
> +	GetResponse(ctx context.Context, path string,
文件下载得返回整个response处理

2023-03-01 08:32 UTC, kinsolee commented on plugin/storage/client/client.go
> +	ForGroupVersion(gv *schema.GroupVersion) Interface
添加method 方便单测assertion

2023-03-01 08:37 UTC, kinsolee commented on sharedmain/app.go
> +	flag.IntVar(&WebServerPort, "web-server-port", 8100, "http web server port")
添加web-server-port 解决本地启动两个http server时冲突问题

2023-03-01 08:55 UTC, kinsolee commented on apis/storage/v1alpha1/filemeta_types.go
> -
因为contract在core仓库，对齐使用 contract 的常量值，搬到core仓库

2023-03-02 05:37 UTC, chengjingtao commented on apis/storage/v1alpha1/labels_annotations.go
> +const LastModifiedAnnotation = "storage.katanomi.dev/lastModified"
这个在什么时候会用到？

2023-03-02 05:45 UTC, kinsolee commented on apis/storage/v1alpha1/labels_annotations.go
> +const LastModifiedAnnotation = "storage.katanomi.dev/lastModified"
用在报告文件清理的时候判断文件是否过期

2023-03-02 06:30 UTC, chengjingtao requested changes

2023-03-02 06:30 UTC, chengjingtao commented on system/cluster.go
> +	return "default"
是不是应该换一个不常见的 ， 例如 -  ？ 或者 ~

2023-03-02 08:12 UTC, kinsolee commented on command/options/path.go
> +	PathKtnSettingCli = "ktn-task"
这个在core仓库已经说明了哈
https://github.com/katanomi/core/pull/225#discussion_r1122699880

2023-03-03 02:31 UTC, chengjingtao approved these changes

2023-03-03 02:39 UTC, merged