feat: add copyImage method.
katanomi/pkg pull request #428
Opened 2023-04-12 14:49 UTC by Jeremy-boo

# Changes
The method of adding copyImage in pkg supports copying images in docker-archive and remote registry.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-04-13 06:46 UTC, Jeremy-boo commented on go.mod
> +	github.com/go-openapi/spec v0.20.8 // indirect
本地执行make test的变化

2023-04-13 06:46 UTC, Jeremy-boo commented on go.mod
>  	k8s.io/client-go v0.26.1
go mod tidy 自动带来的改变

2023-04-14 07:06 UTC, airycanon requested changes

2023-04-14 09:47 UTC, airycanon approved these changes

2023-04-14 10:11 UTC, merged