Feat/cloudevents send
katanomi/pkg pull request #444
Opened 2023-05-23 13:26 UTC by chengjingtao

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-05-23 14:32 UTC, chengjingtao commented on client/context.go
> +}
说明：
提供 注入 cloudevent client  到 context 的能力。 这样业务逻辑发送事件时可以使用

2023-05-23 15:28 UTC, chengjingtao commented on webhook/admission/transform.go
> +}
补充单测

2023-05-23 15:30 UTC, chengjingtao commented on apis/meta/v1alpha1/updatedBy_types.go
单测 @NigelZHANG

2023-05-23 15:30 UTC, chengjingtao commented on apis/meta/v1alpha1/deletedBy_types.go
单测 @NigelZHANG

2023-05-24 14:38 UTC, chengjingtao commented
目前流水线不过是 缺少部分单测导致的， 会补全单测后，确保流水线通过

2023-05-24 14:45 UTC, danielfbm requested changes

2023-05-24 14:45 UTC, danielfbm commented on apis/meta/v1alpha1/cloudevent.go
> +	CloudEventExtRevisionPusher    = "revisionpusher"
revisionauthor ?

2023-05-24 14:45 UTC, danielfbm commented on apis/meta/v1alpha1/cloudevent.go
> +	CloudEventExtRevisionPusher    = "revisionpusher"
`pusher` 有一种不太友好的感觉

2023-05-24 14:45 UTC, danielfbm commented on apis/meta/v1alpha1/gitoption_types.go
> +	Commit string            `json:"commit,omitempty"`
缺少注释描述字段？

2023-05-24 14:45 UTC, danielfbm commented on apis/meta/v1alpha1/updatedBy_types.go
> +}
赞同，感觉都是一样的

2023-05-24 14:45 UTC, danielfbm commented on config/manager.go
> +}
放在 testing 目录下也OK，感觉不应该放在这里

2023-05-24 14:45 UTC, danielfbm commented on user/context.go
> +func EntityFromContext(ctx context.Context) *unstructured.Unstructured {
两个函数需要注释

2023-05-24 14:45 UTC, danielfbm commented on user/filters.go
这种说明可以放在文件的注释里面吧，PR的解释更多的是不适合放在代码里再补充

2023-05-24 14:45 UTC, danielfbm commented on user/filters.go
> +func UserOwnedResourcePermissionFilter(appCtx context.Context, gvr *schema.GroupVersionResource) restful.FilterFunction {
同上，函数都需要注释

2023-05-24 14:45 UTC, danielfbm commented on user/filters.go
> +		if userInReq.GetName() != usernameOfResource {
跟上面一样的道理，用注释解释？

另外这个函数复杂度明显很高，拆成多个函数吧

2023-05-24 14:45 UTC, danielfbm commented on user/ginkgo.report
> +[
这个文件不应该提交？ @chengjingtao

2023-05-24 14:45 UTC, danielfbm commented on webhook/admission/transform.go
> +}
逻辑可以抽出统一的部分，避免三遍都需要单独维护

2023-05-27 08:13 UTC, chengjingtao commented on user/ginkgo.report
> +[
已删除

2023-05-27 08:13 UTC, chengjingtao commented on client/rbac_filter.go
> +func ImpersonateUser(req *http.Request) user.Info {
已添加

2023-05-27 08:14 UTC, chengjingtao commented on apis/meta/v1alpha1/git_revision.go
> +	RevisionPusher string `json:"revisionPusher,omitempty"`
经沟通已经改成了 Submitter

2023-05-27 08:14 UTC, chengjingtao commented on apis/meta/v1alpha1/git_revision.go
> +	RevisionPusher string `json:"revisionPusher,omitempty"`
如沟通，改成了Submitter, 即为 Revision.Submitter

2023-05-27 08:15 UTC, chengjingtao commented on apis/meta/v1alpha1/cloudevent.go
> +	CloudEventExtRevisionPusher    = "revisionpusher"
如沟通，改成了 revisionsubmitter

2023-05-27 08:17 UTC, chengjingtao commented
WithDeletedBy 实际上是无用的。根据 https://book.kubebuilder.io/reference/admission-webhook.html ，目前 仅支持  Create 和 Update。 所以我把 WithDeletedBy 删掉了。
后边 WithUpdateBy 和 WithCreateBy 和 WithTriggeredBy的 统一， 就还给 家杰了。 @NigelZHANG

2023-05-29 01:16 UTC, danielfbm commented on apis/meta/v1alpha1/objectcondition_set_test.go
> +	g.Expect(actual).Should(BeEquivalentTo(expected))
后面需要考虑加更多的测试用例？

2023-05-29 01:17 UTC, danielfbm commented on apis/meta/v1alpha1/objectcondition_set_test.go
> +	g.Expect(actual).Should(BeEquivalentTo(expected))
可以加一个TODO

2023-05-29 01:17 UTC, danielfbm commented on apis/meta/v1alpha1/objectcondition_set_test.go
> +	g.Expect(*actual).Should(BeEquivalentTo(expected))
同上

2023-05-29 01:17 UTC, danielfbm commented on apis/meta/v1alpha1/objectcondition_set_test.go
> +	g.Expect(*actual).Should(BeEquivalentTo(expected))
注释的代码删掉？

2023-05-29 01:25 UTC, danielfbm commented on apis/meta/v1alpha1/updatedBy_types.go
> +}
这个还没统一？ @chengjingtao  @NigelZHANG

2023-05-29 01:26 UTC, danielfbm commented on client/rbac_filter_test.go
> +	req.Header.Del(authnv1.ImpersonateUserHeader)
用不同的 `t.Run` 来区分测试用例

2023-05-29 07:27 UTC, chengjingtao commented on apis/meta/v1alpha1/objectcondition_set_test.go
> +	g.Expect(actual).Should(BeEquivalentTo(expected))
已经增加了新的 测试用例。

2023-05-29 07:28 UTC, chengjingtao commented on client/rbac_filter_test.go
> +	req.Header.Del(authnv1.ImpersonateUserHeader)
已增加修改

2023-05-29 07:41 UTC, danielfbm approved these changes

2023-06-02 07:52 UTC, danielfbm approved these changes

2023-06-02 08:08 UTC, merged