Add ControllerChecker to use in lazyLoad
katanomi/pkg pull request #474
Opened 2023-08-10 07:25 UTC by hawkli-1994

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-08-15 04:32 UTC, chengjingtao requested changes

2023-08-15 04:32 UTC, chengjingtao commented on controllers/lazyloader.go
> +			c.Infow("try check crd installed", "ctrl", item.checker.Name())
checkPending 是 定期执行的， 改成debug ?

2023-08-15 04:32 UTC, chengjingtao commented on controllers/lazyloader.go
> +				c.Debugw("controller setup is pending by crds", "ctrl", item.checker.Name(), "err", err)
记得确保 返回的 err信息里边 能够支持 故障排查

2023-08-15 04:32 UTC, chengjingtao commented on controllers/module_installed_checker.go
> +// ModuleInstalledChecker is the interface for checking if a module is installed
解释下module 和 crd 之间的关系？

2023-08-15 04:32 UTC, chengjingtao commented on sharedmain/app.go
> +func (a *AppBuilder) Controllers(ctors ...controllers.ControllerChecker) *AppBuilder {
这个是一个不兼容的改动。 这个应该会导致 所有依赖这个逻辑的 插件（客户 自己定制的） 升级了pkg 包之后，就无法编译了？

2023-08-15 13:51 UTC, hawkli-1994 commented on controllers/module_installed_checker.go
> +// ModuleInstalledChecker is the interface for checking if a module is installed
重命名了DependencyCheckerInterface

2023-08-15 13:51 UTC, hawkli-1994 commented on sharedmain/app.go
> +func (a *AppBuilder) Controllers(ctors ...controllers.ControllerChecker) *AppBuilder {
重构了, 改回去了, 然后lazyload动态判断

2023-08-15 13:52 UTC, hawkli-1994 commented on controllers/lazyloader.go
> +				c.Debugw("controller setup is pending by crds", "ctrl", item.checker.Name(), "err", err)
crds在实现里打印了

2023-08-16 01:44 UTC, chengjingtao approved these changes

2023-08-16 01:44 UTC, chengjingtao commented
看一下 downstream test 的问题。

2023-08-16 09:48 UTC, chengjingtao approved these changes

2023-08-16 10:16 UTC, merged