Feat/GitHub
katanomi/pkg pull request #487
Opened 2023-10-16 03:10 UTC by kycheng

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

2023-10-16 05:59 UTC, nanjingfm commented on testing/plugins/gitplugin/cases/branch.go
> +				_, *localRepoPath = createRepository(ctx, instance, gitRepo, v1alpha1.GitRepositoryVisibilityPrivate)
每次执行case 会创建一个新的repository。

因为创建repository 比较麻烦，部分case 会在同一个repository 下完成。

2023-10-16 06:00 UTC, nanjingfm commented on testing/plugins/gitplugin/cases/repository.go
> +	localRepoPath, err := gitplugin.InitRepo(testCtx, repo.Spec.HttpCloneURL)
这里调用shell 脚本来初始化repo

2023-10-16 07:12 UTC, kycheng commented on test/plugins/gitplugin/script.go
> +func CreatNewBranch(ctx context.Context, branchName string) (err error) {
typo

2023-10-16 07:14 UTC, danielfbm requested changes
已经review了19个文件，你们先改一下后面我再继续review

2023-10-16 07:14 UTC, danielfbm commented on apis/meta/v1alpha1/gitoption_types.go
> -
哪里都没有用到吗？确定不会break哈

2023-10-16 07:14 UTC, danielfbm commented on git/format.go
> +func FormatPRReference(prID string, isGitlab bool) string {
很奇怪，为啥需要区分 gitlab？这个算是一个反插件化实现，改一下

2023-10-16 07:14 UTC, danielfbm commented on git/ref.go
> +	PrNumber int
这里也是

2023-10-16 07:16 UTC, nanjingfm commented on apis/meta/v1alpha1/gitoption_types.go
> -
转移到单独的文件中去了apis/meta/v1alpha1/gittag_types.go

2023-11-03 02:22 UTC, nanjingfm commented on slices/slices.go
> +func InList[T comparable](list []T, item T) bool {
直接删除

2023-11-03 02:23 UTC, nanjingfm commented on git/doc.go
> +package git
整个git 目录移除

2023-11-09 02:45 UTC, nanjingfm requested changes

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/branch.go
> +					Branch: "test-a",
因为是共享的一个repo，所以beforeach里面创建分支，不同的case 是可能会互相影响的。

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/branch.go
> +	err := CreatNewBranch(testCtx, payload.Branch)
```suggestion
	err := CreateNewBranch(testCtx, payload.Branch)
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/commit.go
> +			payload.Spec.Message = fmt.Sprintf("commit message %d", i)
这里最好支持批量创建，现在是创建一个commit 提交一次，话费的时间比较长

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/commit.go
> +		Expect(err).Should(BeNil())
这行可以移除，It 里面判断了

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/commit.go
> +			It("return commit messgae include search value", func() {
```suggestion
			It("return commit message include search value", func() {
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/commit.go
> +func createCommit(testCtx context.Context, _ TestablePlugin, payload codev1alpha1.CreateGitCommitOption) {
TestablePlugin 没用到就去掉吧。
然后CreateGitCommitOption 这个结构体有点复杂，使用起来不方便，建议再包一个方法，直接传ctx, branch, message

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/project.go
> +	Context("list perject successfully", func() {
```suggestion
	Context("list project successfully", func() {
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/project.go
> +			projectName = pointer.String("not-exist-not-exist-not-exist")
```suggestion
			*projectName = "not-exist-not-exist-not-exist"
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/project.go
> +			projectName = pointer.String(instance.GetTestOrgProject())
同上

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/project.go
> +		projectName string
```suggestion
		projectName = "create-project-" + rand.String(4)
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/project.go
> +	})
还是要保持一定的结构，直接It 放在最外层有点奇怪
```suggestion
    AfterAll(func() {
		cleanupProject(ctx, instance, projectName)
	})
    When("first create project", func() {
        It("should create successfully", func() {
            project, err = creator.CreateProject(ctx, project)

            Expect(err).Should(BeNil())
            Expect(project).ShouldNot(BeNil())
            Expect(project.GetName()).Should(Equal(projectName))
            checkProjectRequired(project)
        })
    })
     When("create an existed project", func() {
        It("should create failed", func() {
            project, err = creator.CreateProject(ctx, project)

            Expect(err).ShouldNot(BeNil())
		    Expect(project).Should(BeNil())
        })
    })
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +				if gitRepo.Project == "" {
判断可以往上放

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +		Context("page turning of repositroy list", func() {
```suggestion
		Context("page turning of repository list", func() {
```

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +				if gitRepoTwoPageList.TotalItems < 10 {
repo 可以自动化创建出来10个，也可以少创建点，然后下面分页参数传小点

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +					Skip(fmt.Sprintf("At least 2 repositories are required under the tool project %s to run the current use case.", gitRepo.Project))
同上，可以考虑一次性把repo创建好，然后再执行case

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +			When("sort by createTime, and asc", func() {
这些case 可以减少点，只需要有：
1.默认参数
2. sort by 和 order by 都不是默认参数的

2023-11-09 02:45 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +			When("sort by createTime, and asc", func() {
保证主流程是对的，不需要枚举出所有的组合

2023-11-09 07:47 UTC, nanjingfm commented on testing/testcases/gitplugin/script.go
> +func CreateMuiltCommit(ctx context.Context, branchName, message string, quantity int) (err error) {
```suggestion
func CreateMultiCommit(ctx context.Context, branchName, message string, quantity int) (err error) {
```

2023-11-09 07:51 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/branch.go
> +			createBranch(ctx, instance, v1alpha1.CreateBranchPayload{
因为是同一个代码仓库，下面两个when 会重复创建相同的分支，

可以放在BeforeAll 里面

2023-11-09 07:53 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +				wantGitRepo, _ = createRepository(ctx, instance, gitRepo, v1alpha1.GitRepositoryVisibilityPrivate)
下面有两个It ，这里会指定两遍

2023-11-09 07:54 UTC, nanjingfm commented on testing/testcases/gitplugin/cases/repository.go
> +				wantGitRepo, _ = createRepository(ctx, instance, gitRepo, v1alpha1.GitRepositoryVisibilityPrivate)
同上

2023-11-09 07:58 UTC, nanjingfm approved these changes

2023-11-09 08:17 UTC, closed without merging