feat:add git interface, webserver and struct for repofile, commit, br…
katanomi/pkg pull request #50
Opened 2021-08-30 01:11 UTC by XiaoBoya

…anch, pr

2021-08-31 03:03 UTC, danielfbm requested changes
整体在看一下这些修改的意见

2021-08-31 03:03 UTC, danielfbm commented on plugin/route/gitcommit.go
> +		tags: []string{"projects", "repositories", "commit"},
这个tag好像不太对，是不是应该是 git 相关的 + commit ？

2021-08-31 03:03 UTC, danielfbm commented on plugin/route/gitbranch.go
> +		tags: []string{"projects", "repositories", "branch"},
tag不太对，跟project没有什么关系？是不是 git 和 branch有关系的？

2021-08-31 03:03 UTC, danielfbm commented on plugin/route/gitpullrequest.go
> +		tags: []string{"projects", "repositories", "pull request"},
同上

2021-09-01 08:20 UTC, XiaoBoya commented on plugin/client/interface.go
> +	GetGitPullRequest(ctx context.Context, option metav1alpha1.GitPullRequestOption) (metav1alpha1.GitPullRequest, error)
嗯，get,list和create都放在一起了（gitlab、github、gitea三个方法都支持，gogs不支持pr这种资源类型的操作）

2021-09-01 15:51 UTC, XiaoBoya commented on apis/meta/v1alpha1/createmeta_types.go
> +}
这个当时设计的时候没有，因为这个是一个特殊的请求，虽然是创建的文件，但是本质上来说是一件特定场景的commit的创建

2021-09-02 13:16 UTC, danielfbm commented on apis/meta/v1alpha1/createmeta_types.go
> +	Title       string
Title 没有`json` tag?

2021-09-02 13:18 UTC, danielfbm commented on apis/meta/v1alpha1/gitbase_types.go
> +	TimeAt *string          `json:"timeAt,omitempty"`
`TimeAt` 是一个 `time`? 是不是用 metav1.Time 会更合适一些？

如果是 time的话建议用 `Time *metav1.Time `json:"time,omtiempty"`

2021-09-02 13:29 UTC, danielfbm requested changes
上次review没有注意到一个比较麻烦的问题：API路径跟镜像仓库的匹配不上，需要加一个 `/projects/{project}/` 前缀

2021-09-02 13:32 UTC, danielfbm commented on apis/meta/v1alpha1/gitpullrequest_types.go
> +	ListMeta
```ListMeta        `json:"metadata,omitempty"````

其他列表也都检查一下哈

2021-09-04 16:25 UTC, danielfbm submitted a review, later dismissed

2021-09-04 16:26 UTC, danielfbm commented
lgtm 

please fix the check errors

2021-09-05 02:27 UTC, danielfbm approved these changes

2021-09-05 02:28 UTC, merged