add reconciler wrapper
katanomi/pkg pull request #500
Opened 2023-11-20 06:58 UTC by airycanon

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included
- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-11-21 04:26 UTC, chengjingtao requested changes

2023-11-21 04:26 UTC, chengjingtao commented on config/feature_flags.go
> +	IntegrationSyncPeriodKey = "integration.syncPeriod"
所有的 key 是不是可以统一？ 比如叫做 core.katanomi.dev/controller.syncPeriod  （举例）？ 这样其他资源如果需要了， 大家都一样。

2023-11-21 04:26 UTC, chengjingtao commented on config/feature_flags.go
> +	DefaultClusterIntegrationSyncPeriod = "2m"
时间要不要调大一些？ 至少 5m 吧。

我始终觉得我们不应该过于依赖这个定期同步的行为。插件是用户自己定制的， 用户定制的质量是不好控制的。 加上整体的定期同步的机制，会放大插件的 行为， 从而导致 对后边工具产生不良的影响。这些从平台框架设计层面就直接增加了系统脆弱的可能性。

我们现在没啥更理想的方案，可能就先这样了。

2023-11-21 07:25 UTC, airycanon commented on config/feature_flags.go
> +	IntegrationSyncPeriodKey = "integration.syncPeriod"
不能统一，可能每个组件的时间要求不太一样，也可以过像 logging 那样，动态读取 xxx.syncPeriod，这样只改配置文件就可以了，考虑到这个配置是按需增加的，用一个通用的隐式配置不太合适，所以没有提供。

2023-11-21 11:23 UTC, chengjingtao approved these changes

2023-11-30 10:38 UTC, danielfbm approved these changes

2023-11-30 13:27 UTC, merged