feat: add BaseGitStatus methods & const for git file
katanomi/pkg pull request #508
Opened 2023-12-04 13:49 UTC by kinsolee

# Changes
add BaseGitStatus methods & const for git file

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [`spec` PR link](https://github.com/katanomi/spec) included

- [ ] Follows the [commit message standard](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md#commits)
- [ ] Meets the [contributing guidelines](https://github.com/katanomi/spec/blob/main/CONTRIBUTING.md) (including
  functionality, content, code)
- [ ] Test cases with documentation and functionality works as expected using current and related github repos (MUST deploy and check)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

2023-12-06 07:57 UTC, kinsolee commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +func (b *BaseGitStatus) IsPR() bool {
这两个方法是从builds仓库提取出来的，后面会替换掉 builds 原来的部分。

2023-12-06 08:23 UTC, danielfbm requested changes

2023-12-06 08:23 UTC, danielfbm commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +}
不太清楚为啥里面所有的字段都得初始化？很多情况是通过 判断 PullRequest 是否非nil来判断是否一个PR，而且这样如果没有用到就浪费了内存，建议移除这种函数

2023-12-06 10:21 UTC, kinsolee commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +}
这个我理解是用来减少在调用前忘记判断是否nil的负担，因为这么多个字段都是指针类型，很容易漏写判断。

类似这样的写法，应该可以使用一个公共的方法替代。
https://github.com/katanomi/builds/blob/2cc2dd9dfeec2c42fdf6868780c427a7021aad90/pkg/controllers/builds/buildrun_controller.go#L1037

而设置为指针类型的原因应该是为了输出为json时支持omitempty。

2023-12-06 10:33 UTC, danielfbm commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +}
理解了，但我认为这个不是一个好实现思路，因为不同的业务对那些字段的依赖是不一样的，我理解正常的使用是要考虑这个字段是否空然后会有具体的业务含义，比如 PullRequest非nil的情况下应该可以自然认为这个就是一个PR的场景。另外json tag的omitempty也是在pointer会以nil和非nil做判断，非nil就会返回一个空的结构体，`{"pullRequest":{}}` 所以你说的不成立。

2023-12-06 11:34 UTC, kinsolee commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +}
“正常的使用是要考虑这个字段是否空然后会有具体的业务含义” 这个赞同，是否为 nil 的确可以用来做业务上的判断。

但是在某些业务场景里，只是关心某几个指针字段下的值，没有就返回空值，比如sonar扫描task构造分支名称，需要同时判断获取：gitStatus.lastCommit.id，gitStatus.revision.id，gitStatus.branch.name 
![CleanShot 2023-12-06 at 19 09 17@2x](https://github.com/katanomi/pkg/assets/5144108/e42b24a3-65c6-4a21-a2ec-9ed6238ab253)

如果取值的地方都判断一下是否为nil，代码的可读性会变差，同时开发者也需要较多心智去留意所在业务是否有空指针导致 panic 的问题。

针对这样的场景先初始化好了，后续无论取哪个字段的值都不用再去确认是否需要判断nil了。
这个初始化的操作也是适用于其他单纯取值的场景，感觉可以保留下来？或者考虑对这种单纯取值的场景有更好的处理方式。

omitempty 在非nil的时候返回的空结构体会包含所有子字段，返回无效信息太多：
`{"pullRequest":{"id":0,"num":0,"title":"","state":"","createdAt":null,"target":{"name":""},"source":{"name":""},"author":{"name":"","email":""},"mergedBy":{"name":"","email":""}}}`
一般输出时期望是 nil 值可以最大化发挥omitempty的作用。

2023-12-07 01:43 UTC, danielfbm commented on apis/meta/v1alpha1/buildmetadata_funcs.go
> +}
实现自己的功能时无论如何都得考虑这种情况，这个并不是我们需要初始化所有的结构体的理由而且明显这种实现会导致其他地方业务使用比较模糊

2023-12-07 09:52 UTC, danielfbm submitted a review, later dismissed

2023-12-11 14:47 UTC, l-qing approved these changes

2023-12-11 15:24 UTC, merged