change
katanomi/pkg pull request #58
Opened 2021-09-04 02:13 UTC by yuzp1996

2021-09-04 02:14 UTC, yuzp1996 commented
This PR is not need merge

2021-09-05 01:56 UTC, danielfbm requested changes
PR title改成一个具体的change吧，否则搜索等等都没法做

2021-09-05 01:56 UTC, danielfbm commented on plugin/client/gitpullrequest.go
> +	// 而且我那边只能获取到 https://gitlab.com/yuzp1996/gitlabzpyu 这个信息  我是拿不到 repoID 的   所以需要这边做一个转换
英文注释

2021-09-05 01:56 UTC, danielfbm commented on plugin/client/gitpullrequest.go
> +	// 而且我那边只能获取到 https://gitlab.com/yuzp1996/gitlabzpyu 这个信息  我是拿不到 repoID 的   所以需要这边做一个转换
避免留下存在的账号信息

2021-09-05 14:18 UTC, yuzp1996 commented
Sorry for open this PR  maybe I should use another way to indicate my change which I want others to make 

I  will close this PR right now

2021-09-05 14:18 UTC, closed without merging